---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 17/08/2022 22:07
---

local checkerImage = love.graphics.newImage("images/checkerboard.png")
checkerImage:setWrap("repeat", "repeat")

function fillCheckerBoard()
    checkerQuad = love.graphics.newQuad( 0,0,
        love.graphics.getWidth(),love.graphics.getHeight(),
        16,16
    )
    love.graphics.draw(checkerImage, checkerQuad, 0,0, 0, 1,1)

end
