---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 15/05/2022 18:32
---

function drawSprite(x,y,_,srcX,srcY,w,h)
    quad = love.graphics.newQuad(srcX, srcY, w, h, sprite:getWidth(), sprite:getHeight())
    love.graphics.draw(sprite, quad, x, y)
end
