---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 19/08/2022 11:56
---

sumT = {0,8,24}
greySumT = {-1,56,32,0} -- -1:unused
greyMaxT = {-1,9,8,5}
pltfrmClrCoord = {300}
-- barrier key color names
colorT = {"red","green","blue","yellow"}
keys = {true,true,true,true} -- make the barrier colors always lit
-- brickT constants
greyVariations = {-1, 11, 7 , 5}


specialDefs = {}
specialDefs[8] = {sType=8,pType=1,w=16,h=6,amnt=0,arrows=1} -- refactor: platform. pType = platform type.
specialDefs[9] = {sType=9,w=18,h=6,direction=4,distance=10,grating=1} -- w and h in horiz 'right' direction. auto adjusted when object is rotated. Total visible dim.
specialDefs[10] = {sType=10,w=16,h=4,direction=4,distance=10} -- magnet
specialDefs[11] = {sType=11,w=18,h=5,direction=4,distance=10,rotates=1} -- rotator
specialDefs[12] = {sType=12,w=15,h=3,direction=4,distance=10,speed=1,rate=1,balls={}} -- Cannon
specialDefs[13] = {sType=13,w=13,h=3,direction=1,distance=10,speedMin=1,speedMax=1,fixdGap=2,gapSize=40,chngOften=2,pos1=20,pos2=20} -- rods
specialDefs[14] = {sType=14,w=14,h=12,direction=4,distance=10,pos=60,endStone=1,XtoY=1,actW=10,actH=6} -- 1-ways
specialDefs[15] = {sType=15,w=14,h=6,direction=4,distance=10,pos=60,endStone=1,actW=10,actH=6,red=2,green=2,blue=2,yellow=2} -- refactor: barriers that require a key?

specialVars={}
specialVars[8]= {
    {"pType",1,{"Home","Freight","Fuel","Extras","Key"}},
    {"w",12,28,4},
}-- platform: name,min,max,step
specialVars[9] = {
    {"direction",1,{"up","down","left","right"}},
    {"distance",1,60,1},
    {"grating",1,{"yes","no"}}
}
specialVars[10] = {
    {"direction",1,{"up","down","left","right"}},
    {"distance",1,60,1},
}
specialVars[11] = {
    {"direction",1,{"up","down","left","right"}},
    {"distance",1,60,1},
    {"rotates",1,{"left","right"}}
}
specialVars[12] = {
    {"direction",1,{"up","down","left","right"}},
    {"distance",6,200,1},
    {"speed",1,10,1},
    {"rate",1,78,2}
}
specialVars[13] = {
    {"direction",1,{"horiz","vert"}},
    {"distance",6,100,1},
    {"speedMin",1,10,1},
    {"speedMax",1,10,1},
    {"chngOften",1,{"yes","no"}},
    {"fixdGap",1,{"yes","no"}},
    {"gapSize",8,160,8}
}
specialVars[14] = {
    {"direction",1,{"up","down","left","right"}},
    {"distance",2,19,1},
    {"actW",4,60,2},
    {"actH",4,60,2},
    {"XtoY",1,{"1 to 2","2 to 1"}},
    {"endStone",1,{"yes","no"}}
}

specialVars[15] = {
    {"direction",1,{"up","down","left","right"}},
    {"distance",2,19,1},
    {"actW",4,60,2},
    {"actH",4,60,2},
    {"endStone",1,{"yes","no"}},
    {"red",1,{"yes","no"}},
    {"green",1,{"yes","no"}},
    {"blue",1,{"yes","no"}},
    {"yellow",1,{"yes","no"}}
}

pltfrmDefs = {
    {{"arrows",1,{"yes","no"},val=1}}, -- home
    {{"amnt",0,11,val=1},--freight
     {"type",0,3,val=0}},
    {{"amnt",0,11,val=1}},--fuel
    {{"type",1,{"turbo","life","cargo"},val=1},
     {"amnt",0,1,val=1}},--Extras
    {{"color",1,colorT,val=1},
     {"amnt",0,1,val=1}}
}

blockNames = {
    [3] = "Red",
    [4] = "Yellow",
    [5] = "Blue",
    [6] = "Green",
    [7] = "Grey",
    [8] = "Platform",
    [9] = "Blower",
    [10] = "Magnet",
    [11] = "Rotator",
    [12] = "Cannon",
    [13] = "Rod",
    [14] = "1-way",
    [15] = "Barrier"
}
