---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 13/05/2022 16:58
---

local bit32 = require("bit")
local unpack = love.data.unpack

function inspect(tbl)
    for i,item in pairs(tbl) do
        print(i,item)
    end
end

function table.sum(tbl)
    local sum = 0
    for i,item in pairs(tbl) do
        sum = sum + item
    end
    return sum
end

function love.conf(t)
    t.console = true
end

function love.draw()

end

local function assertHeader(self, name)
    print(name)
    local magicOrHeader = self:read(4)
    if(magicOrHeader == name) then return end
    assert(self:read(4) == name)
end

local function readInt(self, amount, bytesPerInt)
    result = {}
    if amount < 1 then
        return result
    end
    for i = 1,amount do
        result[i] = unpack("<i"..bytesPerInt, self:read(bytesPerInt))
    end
    return result
end

-- split a byte into first and second unsigned 4-bit numbers
local function splitByte(byte)
   return {
       bit32.rshift(byte, 4),
       bit32.band(byte, 15) -- mask lowest 4 bits
   }
end

function love.load()
    local fp = io.open("nino1.cgl", "rb")
    print("file", fp, type(fp))

    -- file header
    assertHeader(fp, "CGL1")

    assertHeader(fp, "SIZE")
    local size = readInt(fp, 2, 4)
    inspect(size)

    assertHeader(fp, "SOIN")
    local soin = readInt(fp, size[1]*size[2], 1)
    for i,item in ipairs(soin) do
        soin[i] = bit32.band(item, 127) -- ignore most significant bit
    end
    inspect(soin)
    numSobs = table.sum(soin)

    assertHeader(fp, "SOBS")
    local sobs = {}
    for i = 1, numSobs do
        local tile = readInt(fp, 4, 1)

        sobs[i] = {
            splitByte(tile[1]),
            splitByte(tile[2]),
            tile[3],
            tile[4]
        }
    end

    print("numsobs", numSobs, #sobs)
    inspect(sobs[1][2])


    assertHeader(fp, "VENT")
    local numFans = readInt(fp, 1, 4)[1]
    print("numFans", numFans)
    readInt(fp, numFans * 38, 1)
    assertHeader(fp, "MAGN")

    love.event.quit()

end
