---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 19/08/2022 13:59
---

local gfx = love.graphics

class("MenuView").extends()

function MenuView:init(menuViewModel)
    self.menuViewModel = menuViewModel
    self.header = menuViewModel.header
    self.data = menuViewModel.list
end

local menuPadding = 15
function MenuView:draw()
    local menuX, menuY, menuW, menuH = 100, 100, 125, 45+#self.data*12-3
    local x = menuX + menuPadding
    local y = menuY + menuPadding
    local hMiddle = menuX + menuW/2
    fillRect(menuX, menuY, menuW, menuH, semiWhite)
    gfx.setColor(black)
    gfx.print(self.header, x, y)

    y = y + 15

    for i,item in ipairs(self.data) do
        if i==self.menuViewModel.menuSel then
            gfx.print(">", x - 10,y)
        end
        gfx.print(item[1],x,y)
        if type(item[3])=="table" then
            printf(item[1],item.val)
            gfx.print(item[3][item.val], hMiddle, y)
        else
            printf(item[1])
            --menuFont:print(254,79+i*12,black,string.format("%0.2f",item.val))
            gfx.print(Trunc_Zeros(item.val), hMiddle, y)
        end

        y = y + 12
    end

    -- reset gfx
    gfx.setColor(white)
end
