---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 02/07/2022 21:48
---

function rectSelection(x,y,w,h)
    local selection = {}
    for i = x,x+w-1 do
        for j = y, y+h-1 do
            table.insert(selection, {i,j})
        end
    end
    return selection
end

--- fill selection with {0,1,1,0,0} (1x1 empty tile)
--- or {2,1,1,0,0} if markOccupied is true
function clearSelection(selection, markOccupied)
    local brickType = 0
    if markOccupied then
        brickType = 2
    end
    for _, item in ipairs(selection) do
        local curBrick = brickT[item[1]][item[2]]
        if curBrick[1]==7 then
            kmax = curBrick[3]-1-curBrick[4]
            lmax = curBrick[3]-1-curBrick[5]
        else
            kmax = curBrick[2]-1-curBrick[4]
            lmax = curBrick[3]-1-curBrick[5]
        end
        for k = 0-curBrick[4],kmax do
            for l = 0-curBrick[5],lmax do
                brickT[item[1]+k][item[2]+l] = {brickType,1,1,0,0}
            end
        end

    end
end
