---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 25/06/2022 15:02
---

function table.compress(tbl)
    print("--- compressing table")
    local format = "BBBBB"
    levelProps.packFormat = format
    for x, xtem in ipairs(tbl) do
        for y,ytem in ipairs(xtem) do
            -- unpack refers to table.unpack; which returns table entries as extra arguments (vararg)
            xtem[y]=love.data.pack("string", format, unpack(ytem))
        end
    end

    for x, xtem in ipairs(tbl) do
        local compressedColumn = { compressed = xtem}
        local unpackMeta = {
            __index = function(tbl, idx)
                return {love.data.unpack(format, tbl.compressed[idx])}
                -- note will have extra index for string index of next byte
            end
        }
        tbl[x]= setmetatable(compressedColumn, unpackMeta)
    end
end
