---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 18/09/2022 19:07
---

function writeImage(basePath)
    local canvas = love.graphics.newCanvas(levelProps.sizeX*tileSize,levelProps.sizeY*tileSize)
    love.graphics.setCanvas(canvas)
    drawSpecials(camPos, true)
    drawBricks(true)
    love.graphics.setCanvas()
    canvas:newImageData():encode("png",basePath .. ".png")
end
